#!/bin/sh

mydir=/userdata/system/configs/drastic_steward


export LD_LIBRARY_PATH=$mydir/libs:$LD_LIBRARY_PATH
export SDL_VIDEODRIVER=mmiyoo
export EGL_VIDEODRIVER=mmiyoo


cd $mydir

./drastic "$1"
