#!/bin/bash

SERVICES=$(batocera-settings-get system.services)
BOARD=$(cat /boot/boot/batocera.board)
# We only want the script to run for these devices
if [ "$BOARD" != "rg40xx-h" ] && [ "$BOARD" != "rg40xx-v" ] && [ "$BOARD" != "rg-cubexx" ]; then
    exit 1
fi

case "$1" in
    thaw|resume)
        if echo "$SERVICES" | grep -q "analog_stick_led"; then
            /usr/bin/analog_stick_led_daemon.sh restart
        fi
        ;;
esac

exit 0
