#!/bin/bash

MODE="$(/usr/bin/batocera-settings-get system.lid)"
if [[ -z "$MODE" || ! "$MODE" =~ ^(suspend|shutdown)$ ]]; then
    MODE="suspend" # default can be suspend|shutdown
    /usr/bin/batocera-settings-set system.lid "$MODE"
fi

case "$1" in
    start)
            batocera-settings-set system.lid "$MODE"
        ;;
    stop)
            batocera-settings-set system.lid suspend
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac
 
exit $?
