#!/bin/bash

BOARD=$(cat /boot/boot/batocera.board)
# We only want the script to run for rg35xx-sp
if [ "$BOARD" != "rg35xx-sp" ]; then
    exit 1
fi

case "$1" in
    start)
            batocera-settings-set system.lid shutdown
        ;;
    stop)
            batocera-settings-set system.lid suspend
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac
 
exit $?
