#!/bin/bash

log="/tmp/resize.log"

# only at start
test "$1" != "start" && exit 0

mount -o rw,remount /boot
# true if triggers are not available or not set to do so
if [ ! -f /boot/boot/autoresize ]
then
    exit 0
fi

# --- BEGIN RESIZE ---
# remove the trigger
rm -f /boot/boot/autoresize
DISK=/dev/mmcblk0
PART=/dev/mmcblk0p3
PARTNUM=3

cd /root
umount /boot
umount ${PART}

sync

echo -e "1\nd\n3\nn\n3\n7356416\n\n0700\nw\ny\n" | gdisk ${DISK} 

partprobe ${DISK} >> "$log"

sync

mkfs.exfat -n SHARE ${PART} >> "$log"

partprobe ${DISK} >> "$log"

sync

# The first time we start we reboot to make sure the partition changes are permanent
sleep 1
reboot

exit 0

