default:
  options:
    gfxbackend: gl
    video_threaded: true
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: ozone
    retroarch.audio_driver: alsathread
    retroarch.menu_scale_factor: 1.500000

nds:
  emulator: libretro
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark

