default:
  options:
    gfxbackend: gl
    video_threaded: true
    # menu retroarch
    retroarch.menu_driver: ozone
    retroarch.audio_driver: alsathread
    retroarch.menu_scale_factor: 1.500000

nds:
  emulator: advanced_drastic
  core:     advanced_drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
  options:
    hud_support: false
naomi:
  emulator: libretro
  core:     flycastvl
