#!/bin/sh

# The RG40XX-H has swapped audio channels for speakers, but not for headphones.
#
# The new kernel in version 1.0.3 of the stock firmware resolves this bug, but
# we currently use a patched version of an older stock kernel (to fix cardinal
# snapping issues), and upgrading it isn't trivial.
#
# For now, poll spk_state (0 -> headphones plugged, 1 -> headphones unplugged)
# and swap DACL and DACR when the state changes.

DAEMON=/usr/bin/battery-saver.sh
PIDFILE=/var/run/battery-saver.pid
DAEMON_NAME=$(basename "$DAEMON")

start_daemon() {
    echo "Starting $DAEMON_NAME."
    if [ -f "$PIDFILE" ] && start-stop-daemon --status --pidfile "$PIDFILE" > /dev/null 2>&1; then
        echo "$DAEMON_NAME is already running."
        exit 0
    fi

    start-stop-daemon --start --quiet --background --make-pidfile --pidfile "$PIDFILE" --exec "$DAEMON" \
        && echo "$DAEMON_NAME started OK" || { echo "$DAEMON_NAME failed to start"; exit 1; }
}

stop_daemon() {
    echo "Stopping $DAEMON_NAME."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
        && { echo "$DAEMON_NAME stopped"; rm -f "$PIDFILE"; } || { echo "$DAEMON_NAME is not running."; }
}

# Sanity check
test -x $DAEMON || exit 0

case "$1" in
    start)
        start_daemon
        ;;
    stop)
        stop_daemon
        ;;
    restart)
        stop_daemon
        sleep 1
        start_daemon
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
