<?xml version="1.0" encoding="UTF-8"?>
<systemList>
  <system>
        <name>pico8</name>
        <emulators>
            <emulator name="lexaloffle">
                <cores>
                    <core>pico8_official</core>
                </cores>
            </emulator>
            <emulator name="libretro">
                <cores>
                    <core default="true">fake08</core>
                </cores>
            </emulator>
        </emulators>
  </system>
</systemList>