#!/bin/sh

try_headphone_volume() {
    N=20
    while test "${N}" -gt 0
    do
        echo "retry applying audio (${N})" >&2
	value=$(amixer sget "Headphone" | sed -n "s/  Mono: \([0-9]*\) .*/\1/p")
	echo "Value: $value"
	if [ "$value" -eq 4 ]
	then
            return 0
        fi
	amixer set 'Headphone' 4
        sleep 3
	N=$((N-1))
    done
    return 1
}

if test "$1" = "start"
then
    sleep 5
    try_headphone_volume
fi

