#!/bin/bash

SERVICES=$(batocera-settings-get system.services)

case "$1" in
    thaw|resume)
        if echo "$SERVICES" | grep -q "analog_stick_led"; then
            /usr/bin/analog_stick_led_daemon.sh restart
        fi
        ;;
esac

exit 0
