#!/bin/bash

case "$1" in
    start)
		# Code in here will only be executed on start.
		echo -n "Enabling analog stick LED"
		analog_stick_led.sh
        ;;
    stop)
        # Code in here will only be executed on shutdown.
		echo "Not implemented, yet."
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac
 
exit $?