#!/bin/sh

r=200
g=255
b=200
valstr=`printf "%02X%02X%02X" $r $g $b`
echo "$valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr $valstr "\
      "$valstr $valstr $valstr $valstr $valstr $valstr $valstr" > /sys/class/led_anim/frame_hex 

#echo 5 > /sys/class/leds/sunxi_led0r/brightness
#usleep 10000
#echo 5 > /sys/class/leds/sunxi_led0g/brightness
#usleep 10000
#echo 5 > /sys/class/leds/sunxi_led0b/brightness
#usleep 10000

#echo $value > /sys/class/led_anim/max_scale 
