#!/bin/sh

#inicialize the counter for the bar
contador=$(($(ls /etc/init.d/S*|wc -l)-1))
multiplicador=$(echo "100/$contador"|bc -l)


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
            num=$(echo "$multiplicador * $contador" |bc -l)
            contador=$(($contador-1))
            /usr/bin/barra $num
	    $i stop
	    ;;
    esac
done
/usr/bin/barra 0
