#!/bin/sh

# # Disable the IO scheduler (it just ends up slowing down the MicroSD cards)
echo noop > /sys/devices/platform/soc/sdc0/mmc_host/mmc0/mmc0:1234/block/mmcblk0/queue/scheduler
echo noop > /sys/devices/platform/soc/sdc2/mmc_host/mmc1/mmc1:0001/block/mmcblk1/queue/scheduler

# Disable MicroSD card power-saving (helps reduce load stutter)
echo on > /sys/devices/platform/soc/sdc0/mmc_host/mmc0/power/control
echo on > /sys/devices/platform/soc/sdc2/mmc_host/mmc1/power/control

