#!/bin/sh
#
# Starts audio services
#

case "$1" in
    start)
#	value="$(batocera-settings-get audio.volume)"
        alsactl init # init cards with alsa files
        alsactl restore 0 -f /userdata/system/.asound.state

#        amixer sset 'SPK' 'on'
#        amixer sset 'LINEOUT' 'on'
#	amixer sset 'Master' $value
#	amixer sset 'OutputL Mixer DACL' 'on'
#	amixer sset 'OutputL Mixer DACR' 'on'
#	amixer sset 'OutputR Mixer DACL' 'on'
#	amixer sset 'OutputR Mixer DACR' 'on'
    ;;
    stop)
    ;;
    restart|reload)
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
